[tools]
python = "3.12.3"

[env]
_.python.venv = ".venv"

[tasks]
format = "python -m ruff format numerical_methods"
lint = "python -m ruff check --fix numerical_methods"
test = "python -m unittest discover -s numerical_methods -p '*_test.py'"

[tasks.check]
depends = ["format", "lint", "test"]